//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int priceID { get; set; }
        public int userID { get; set; }
        public int price { get; set; }
        public System.DateTime from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public int packageID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Package Package { get; set; }
    }
}
