//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int reservationID { get; set; }
        public int createdByUserId { get; set; }
        public Nullable<int> userID { get; set; }
        public System.DateTime reservationsFrom { get; set; }
        public System.DateTime reservationsTo { get; set; }
        public Nullable<int> numGuests { get; set; }
        public Nullable<bool> isCheckedIn { get; set; }
        public Nullable<bool> isWaitlisted { get; set; }
        public int packageID { get; set; }
        public Nullable<int> packageStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Package Package { get; set; }
    }
}
