//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionID { get; set; }
        public int userID { get; set; }
        public int reservationID { get; set; }
        public string paymentMethod { get; set; }
        public double amountPaid { get; set; }
        public double amountRequired { get; set; }
        public string cardInfo { get; set; }
        public int pointsApplied { get; set; }
        public int pointsEarned { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual User User { get; set; }
    }
}
